public class Mapping {
    public static String getOmschrijving(String[] kolommen, int level) {
        try {
            return kolommen[7+level];
        } catch (ArrayIndexOutOfBoundsException e) {
            return null;
        }
    }

    public static String abstraheren(String key, int level) {
        if (level<1) return key;
        else {
            switch (key) {
// LEVEL1
                case "NR:FKS1BP":return abstraheren("Aldi", level-1);
                case "NR:RY7TF7":return abstraheren("Aldi", level-1);
                case "NR:B6V3ZR":return abstraheren("Aldi", level-1);
                case "NR:2GL402":return abstraheren("Action", level-1);
                case "NR:5H907Y":return abstraheren("Action", level-1);
                case "NR:G1H68T":return abstraheren("Action", level-1);
                case "NR:4L1301":return abstraheren("Lidl", level-1);
                case "NR:4L1303":return abstraheren("Lidl", level-1);
                case "NR:433W2D":return abstraheren("Intertoys", level-1);
                case "NR:6X1WR8":return abstraheren("Poiesz", level-1);
                case "NR:F120WR":return abstraheren("Poiesz", level-1);
                case "NR:FN6QV1":return abstraheren("Poiesz", level-1);
                case "NR:49001207":return abstraheren("Kuhtai", level-1);
                case "NR:58NTR6":return abstraheren("Poiesz", level-1);
                case "NR:5RY0H9":return abstraheren("Lidl", level-1);
                case "NR:XSR769":return abstraheren("Lidl", level-1);
                case "NR:HNZ37F":return abstraheren("Broodzaak", level-1);
                case "NR:C5FJB7":return abstraheren("Keulen", level-1);
                case "NR:Q2RF7S":return abstraheren("Albert Heijn", level-1);
                case "NR:34GJN9":return abstraheren("Albert Heijn", level-1);
                case "NR:7CPP55":return abstraheren("Albert Heijn", level-1);
                case "NR:66C703":return abstraheren("Albert Heijn", level-1);
                case "NR:W540J2":return abstraheren("Albert Heijn", level-1);
                case "NR:W55B0Q":return abstraheren("Albert Heijn", level-1);
                case "NR:W6NQN2":return abstraheren("Albert Heijn", level-1);
                case "NR:W7V03D":return abstraheren("Albert Heijn", level-1);
                case "NR:W806KZ":return abstraheren("Albert Heijn", level-1);
                case "NR:53S740":return abstraheren("Albert Heijn", level-1);
                case "NR:53SF6Y":return abstraheren("Albert Heijn", level-1);
                case "NR:544K6G":return abstraheren("Albert Heijn", level-1);
                case "NR:54G47P":return abstraheren("Albert Heijn", level-1);
                case "NR:54WN2L":return abstraheren("Albert Heijn", level-1);
                case "NR:55RM82":return abstraheren("Albert Heijn", level-1);
                case "NR:567R2K":return abstraheren("Albert Heijn", level-1);
                case "NR:57SD2J":return abstraheren("Albert Heijn", level-1);
                case "NR:58LGH9":return abstraheren("Albert Heijn", level-1);
                case "NR:58QVL1":return abstraheren("Albert Heijn", level-1);
                case "NR:59V1J8":return abstraheren("Albert Heijn", level-1);
                case "NR:27YZG4":return abstraheren("Albert Heijn", level-1);
                case "NR:2D96G4":return abstraheren("Albert Heijn", level-1);
                case "NR:6KZV4B":return abstraheren("Albert Heijn", level-1);
                case "NR:NSW7TD":return abstraheren("Albert Heijn", level-1);
                case "NR:C7TZ5D":return abstraheren("Albert Heijn", level-1);
                case "NR:C8BR7R":return abstraheren("Albert Heijn", level-1);
                case "NR:C8KF23":return abstraheren("Albert Heijn", level-1);
                case "NR:C9W4HZ":return abstraheren("Albert Heijn", level-1);
                case "NR:Q2J3RW":return abstraheren("Albert Heijn", level-1);
                case "NR:Q2PG90":return abstraheren("Albert Heijn", level-1);
                case "NR:Q2QV5M":return abstraheren("Albert Heijn", level-1);
                case "NR:DQ3VT2":return abstraheren("Albert Heijn", level-1);
                case "NR:6D6H9K":return abstraheren("Albert Heijn", level-1);
                case "NR:EL4905":return abstraheren("Albert Heijn", level-1);
                case "NR:EL4906":return abstraheren("Albert Heijn", level-1);
                case "NR:FPL892":return abstraheren("Albert Heijn", level-1);
                case "NR:6L9RBL":return abstraheren("Albert Heijn", level-1);
                case "NR:BT0H30":return abstraheren("Allesco", level-1);
                case "NR:54359951":return abstraheren("AC/DC Hamburg", level-1);
                case "NR:GX6802":return abstraheren("ANWB", level-1);
                case "NR:71014925":return abstraheren("Aral", level-1);
                case "NR:84CXL7":return abstraheren("BA P1 cashless EELDE", level-1);
                case "NR:8GLZ4Q":return abstraheren("Bakkerij Van Esch", level-1);
                case "NR:6F92RC":return abstraheren("Baloney's B.V.", level-1);
                case "NR:SG32TF":return abstraheren("Chinees Bamboe Garden", level-1);
                case "NR:1DQR01":return abstraheren("Bart Smit", level-1);
                case "NR:1DQR02":return abstraheren("Bart Smit", level-1);
                case "NR:65348251":return abstraheren("Bauhaus", level-1);
                case "NR:65348252":return abstraheren("Bauhaus", level-1);
                case "NR:65359928":return abstraheren("Bauhaus", level-1);
                case "NR:48TK01":return abstraheren("Benifit-shop", level-1);
                case "NR:4XS101":return abstraheren("Benner", level-1);
                case "NR:SB2SCZ":return abstraheren("Benner", level-1);
                case "NR:CT109939":return abstraheren("Benzine S. Giezen", level-1);
                case "NR:AH102127":return abstraheren("Kuhtai", level-1);
                case "NR:2LW963":return abstraheren("Binnenpret", level-1);
                case "NR:TH6701":return abstraheren("Blokker", level-1);
                case "NR:TJ0302":return abstraheren("Blokker", level-1);
                case "NR:79R57C":return abstraheren("Boekhandel v/d Velde", level-1);
                case "NR:CW491R":return abstraheren("Boekhandel v/d Velde", level-1);
                case "NR:678K66":return abstraheren("Boomker Boeken", level-1);
                case "NR:33536611":return abstraheren("Kuhtai", level-1);
                case "NR:BS002766":return abstraheren("Bourgondisch Beilen", level-1);
                case "NR:22MZ01":return abstraheren("Bowling Partycentrum", level-1);
                case "NR:71060398":return abstraheren("BP Paddepoel", level-1);
                case "NR:71060399":return abstraheren("BP Paddepoel", level-1);
                case "NR:SJ7HQ3":return abstraheren("Brasserie vd Berg", level-1);
                case "NR:L2V6LR":return abstraheren("Break Out Grunopark", level-1);
                case "NR:KG8503":return abstraheren("Bristol", level-1);
                case "NR:KG8504":return abstraheren("Bristol", level-1);
                case "NR:2JXQ01":return abstraheren("Buckshot Cafe", level-1);
                case "NR:1XRB78":return abstraheren("Cafe de Bres", level-1);
                case "NR:02K401":return abstraheren("Cafe De Keyzer", level-1);
                case "NR:2S6K01":return abstraheren("Cafe de Koffer", level-1);
                case "NR:5KSX01":return abstraheren("Cafe de Minnaar", level-1);
                case "NR:0GRG01":return abstraheren("Cafe de Pintelier", level-1);
                case "NR:14PG8V":return abstraheren("Cafe Mulder", level-1);
                case "NR:38FJ71":return abstraheren("Cafe Ome Ko", level-1);
                case "NR:65D41M":return abstraheren("Cafe Tante Truus", level-1);
                case "NR:FK609X":return abstraheren("Cafetaria Friet van Piet", level-1);
                case "NR:CT395619":return abstraheren("Boven Jan", level-1);
                case "NR:CT401941":return abstraheren("Drie Uiltjes", level-1);
                case "NR:CT398823":return abstraheren("Cafe de Uurwerker", level-1);
                case "NR:CT420614":return abstraheren("Cafe de Uurwerker", level-1);
                case "NR:CT114346":return abstraheren("Bonte Wever", level-1);
                case "NR:CT440514":return abstraheren("Drie Gezusters", level-1);
                case "NR:CT462692":return abstraheren("Drie Gezusters", level-1);
                case "NR:CT462693":return abstraheren("Drie Gezusters", level-1);
                case "NR:CT381110":return abstraheren("Drie Gezusters", level-1);
                case "NR:CT470726":return abstraheren("Euroborg Horeca", level-1);
                case "NR:CT467323":return abstraheren("Interparking", level-1);
                case "NR:CT415152":return abstraheren("Kampeercafe BV Roden", level-1);
                case "NR:CT399465":return abstraheren("Klein Amsterdam", level-1);
                case "NR:AL055235":return abstraheren("Lampenier", level-1);
                case "NR:CT462881":return abstraheren("Lola050", level-1);
                case "NR:CT466080":return abstraheren("Martini Plaza", level-1);
                case "NR:CT385240":return abstraheren("Martini Plaza", level-1);
                case "NR:CT105881":return abstraheren("Muziekhuis Westerhaven", level-1);
                case "NR:CT457835":return abstraheren("Philips Museum", level-1);
                case "NR:CT435961":return abstraheren("Poppodium Simplon", level-1);
                case "NR:CT447247":return abstraheren("Poppodium Simplon", level-1);
                case "NR:CT400731":return abstraheren("Cafe De Buurvrouw", level-1);
                case "NR:CT445641":return abstraheren("Smedema's Poeliersbedrijf", level-1);
                case "NR:CT064715":return abstraheren("Zwembad Hoogkerk", level-1);
                case "NR:AL021899":return abstraheren("Tandarts Geertsema", level-1);
                case "NR:CT435845":return abstraheren("Vera Groningen", level-1);
                case "NR:CT435846":return abstraheren("Vera Groningen", level-1);
                case "NR:CT438928":return abstraheren("Vera Groningen", level-1);
                case "NR:CT470916":return abstraheren("Visspecialist Paddepoel", level-1);
                case "NR:930L5C":return abstraheren("Cigo Station Groningen", level-1);
                case "NR:NS6VMJ":return abstraheren("Coolblue", level-1);
                case "NR:983J99":return abstraheren("Coop", level-1);
                case "NR:986C23":return abstraheren("Coop", level-1);
                case "NR:98C2N8":return abstraheren("Coop", level-1);
                case "NR:996YP4":return abstraheren("Coop", level-1);
                case "NR:59X0KK":return abstraheren("Coop", level-1);
                case "NR:VZZ4SR":return abstraheren("Cor Hamstra", level-1);
                case "NR:7JJF3C":return abstraheren("DA Drogisterij", level-1);
                case "NR:257KSK":return abstraheren("Cafe De Kar", level-1);
                case "NR:JS6101":return abstraheren("De Mannenwinkel", level-1);
                case "NR:71060608":return abstraheren("Tankstation De Panjerd", level-1);
                case "NR:CT390964":return abstraheren("Cafe De Toeter", level-1);
                case "NR:G137K6":return abstraheren("De Vrijbuiter", level-1);
                case "NR:69156027":return abstraheren("DFM Hamburg GmbH & Co.", level-1);
                case "NR:T1Q6F1":return abstraheren("Dinner Served", level-1);
                case "NR:280HWD":return abstraheren("Drouwener Zand", level-1);
                case "NR:WR2003":return abstraheren("Ameland", level-1);
                case "NR:268HR4":return abstraheren("Emmen Noord", level-1);
                case "NR:42M3ND":return abstraheren("Emsland Recreatie", level-1);
                case "NR:2T8R02":return abstraheren("Etos", level-1);
                case "NR:5Q8M9L":return abstraheren("Flitsverkoop/Max", level-1);
                case "NR:FY6502":return abstraheren("Gamma", level-1);
                case "NR:FY6503":return abstraheren("Gamma", level-1);
                case "NR:FY6506":return abstraheren("Gamma", level-1);
                case "NR:68JKN0":return abstraheren("Gall & Gall", level-1);
                case "NR:60942814":return abstraheren("Generator Hostel Hamburg", level-1);
                case "NR:18016588":return abstraheren("Kuhtai", level-1);
                case "NR:AH100716":return abstraheren("Kuhtai", level-1);
                case "NR:21055811":return abstraheren("Gulf", level-1);
                case "NR:CT187807":return abstraheren("Gulf", level-1);
                case "NR:21090011":return abstraheren("Gulf", level-1);
                case "NR:74020008":return abstraheren("Kuhtai", level-1);
                case "NR:1MD403":return abstraheren("H & M", level-1);
                case "NR:ZR7Q93":return abstraheren("De drentse snoepkraam Zuidlaren", level-1);
                case "NR:HQ3501":return abstraheren("Halfords", level-1);
                case "NR:HQ5401":return abstraheren("Halfords", level-1);
                case "NR:T2Q5S8":return abstraheren("Harbour Cafe", level-1);
                case "NR:5LPH01":return abstraheren("Hasret Doner Kebap", level-1);
                case "NR:1LPC01":return abstraheren("Helperzwembad", level-1);
                case "NR:X5C2L6":return abstraheren("HEMA", level-1);
                case "NR:MC9025":return abstraheren("HEMA", level-1);
                case "NR:MC9026":return abstraheren("HEMA", level-1);
                case "NR:MC9009":return abstraheren("HEMA", level-1);
                case "NR:MC9012":return abstraheren("HEMA", level-1);
                case "NR:ME8704":return abstraheren("HEMA", level-1);
                case "NR:ME8708":return abstraheren("HEMA", level-1);
                case "NR:7KJV2Z":return abstraheren("Het Pakhuis", level-1);
                case "NR:01010565":return abstraheren("Pinnen", level-1);
                case "NR:1XJ0B0":return abstraheren("IKEA", level-1);
                case "NR:G49JH3":return abstraheren("IKEA", level-1);
                case "NR:5HGW03":return abstraheren("IKEA", level-1);
                case "NR:5HGW04":return abstraheren("IKEA", level-1);
                case "NR:5HGW05":return abstraheren("IKEA", level-1);
                case "NR:5HGW06":return abstraheren("IKEA", level-1);
                case "NR:5HGW09":return abstraheren("IKEA", level-1);
                case "NR:5HGW10":return abstraheren("IKEA", level-1);
                case "NR:5HGW16":return abstraheren("IKEA", level-1);
                case "NR:006929":return abstraheren("Pinnen", level-1);
                case "NR:025RM0":return abstraheren("Intertoys", level-1);
                case "NR:2C1801":return abstraheren("Intertoys", level-1);
                case "NR:2C1802":return abstraheren("Intertoys", level-1);
                case "NR:QJ6803":return abstraheren("Intertoys", level-1);
                case "NR:43201019":return abstraheren("De Eetfabriek", level-1);
                case "NR:88416101":return abstraheren("Klinkhamer Catering", level-1);
                case "NR:MM8201":return abstraheren("Jacobs Kantoorboekhandel", level-1);
                case "NR:28026893":return abstraheren("Kuhtai", level-1);
                case "NR:2ZWM11":return abstraheren("Jumbo", level-1);
                case "NR:CD2101":return abstraheren("Jumbo", level-1);
                case "NR:140D27":return abstraheren("Jumbo", level-1);
                case "NR:FZR900":return abstraheren("Jumbo", level-1);
                case "NR:75SE08":return abstraheren("Jumbo", level-1);
                case "NR:5ZP1B8":return abstraheren("Jumbo", level-1);
                case "NR:312K69":return abstraheren("Kampeerhal De Vrijbuiter", level-1);
                case "NR:F723S1":return abstraheren("Kassierzuid4", level-1);
                case "NR:54320113":return abstraheren("KFC Keulen", level-1);
                case "NR:80870096":return abstraheren("Pinnen", level-1);
                case "NR:3Z7Y5G":return abstraheren("Kool Automobielbedrijf", level-1);
                case "NR:S1N267":return abstraheren("Pinnen", level-1);
                case "NR:5C1D01":return abstraheren("Kruidvat", level-1);
                case "NR:2ZN801":return abstraheren("Kruidvat", level-1);
                case "NR:2ZN802":return abstraheren("Kruidvat", level-1);
                case "NR:54377142":return abstraheren("Kuhtai", level-1);
                case "NR:27227620":return abstraheren("Kuhtai", level-1);
                case "NR:CT484285":return abstraheren("Le Souk", level-1);
                case "NR:22KJP1":return abstraheren("Leen Bakker", level-1);
                case "NR:T6LZ2N":return abstraheren("McDonald's", level-1);
                case "NR:3R32N9":return abstraheren("McDonald's", level-1);
                case "NR:N0D84N":return abstraheren("McDonald's", level-1);
                case "NR:NP9J47":return abstraheren("McDonald's", level-1);
                case "NR:3Z9BVB":return abstraheren("McDonald's", level-1);
                case "NR:XS046T":return abstraheren("McDonald's", level-1);
                case "NR:2G5L02":return abstraheren("Media Markt", level-1);
                case "NR:2G5L03":return abstraheren("Media Markt", level-1);
                case "NR:2G5L08":return abstraheren("Media Markt", level-1);
                case "NR:5LZK11":return abstraheren("Media Markt", level-1);
                case "NR:ZW4301":return abstraheren("Mediq", level-1);
                case "NR:2Q42FW":return abstraheren("Media Markt", level-1);
                case "NR:54283801":return abstraheren("Motel Pelikan", level-1);
                case "NR:4Z55M0":return abstraheren("Sodexo", level-1);
                case "NR:5WQD01":return abstraheren("Trein", level-1);
                case "NR:5WPB01":return abstraheren("Trein", level-1);
                case "NR:5WPB02":return abstraheren("Trein", level-1);
                case "NR:P9X9V0":return abstraheren("Ozan Doner Kebap", level-1);
                case "NR:M8F9SK":return abstraheren("Ozan Doner Kebap", level-1);
                case "NR:6D3S01":return abstraheren("Pacific", level-1);
                case "NR:0K63QV":return abstraheren("Apenheul", level-1);
                case "NR:6ZKS50":return abstraheren("Parkeren", level-1);
                case "NR:643P5S":return abstraheren("Parkeren", level-1);
                case "NR:V16XPB":return abstraheren("Parkeren", level-1);
                case "NR:2HG704":return abstraheren("Pathe", level-1);
                case "NR:J7V71N":return abstraheren("Pathe", level-1);
                case "NR:QW1YC5":return abstraheren("Pathe", level-1);
                case "NR:CU7903":return abstraheren("Perry Sport", level-1);
                case "NR:65148485":return abstraheren("Taxi", level-1);
                case "NR:CD1236":return abstraheren("Plus", level-1);
                case "NR:702K8V":return abstraheren("Plus", level-1);
                case "NR:243NYJ":return abstraheren("Poiesz", level-1);
                case "NR:30BL01":return abstraheren("Primera", level-1);
                case "NR:335112":return abstraheren("Pinnen", level-1);
                case "NR:00058303":return abstraheren("TKP Ski", level-1);
                case "NR:R57N98":return abstraheren("Ameland", level-1);
                case "NR:6PBG2V":return abstraheren("Kroewa Thai", level-1);
                case "NR:S67VP3":return abstraheren("Restaurant Cairo", level-1);
                case "NR:18018462":return abstraheren("TKP Ski", level-1);
                case "NR:00UE01":return abstraheren("Scapino", level-1);
                case "NR:CPH864":return abstraheren("Garage DMA", level-1);
                case "NR:DZ3W5V":return abstraheren("Le Souk", level-1);
                case "NR:8WVB93":return abstraheren("Shell", level-1);
                case "NR:NS292G":return abstraheren("Shell", level-1);
                case "NR:028114":return abstraheren("Pinnen", level-1);
                case "NR:413N58":return abstraheren("So-Low", level-1);
                case "NR:T5WPF2":return abstraheren("So-Low", level-1);
                case "NR:Y9LH1C":return abstraheren("So-Low", level-1);
                case "NR:09GX03":return abstraheren("Kardinge", level-1);
                case "NR:50018059":return abstraheren("Zwarte Cross", level-1);
                case "NR:6P506L":return abstraheren("Zwarte Cross", level-1);
                case "NR:78TL4S":return abstraheren("Zwarte Cross", level-1);
                case "NR:JJ9C3B":return abstraheren("Zwarte Cross", level-1);
                case "NR:KLV532":return abstraheren("Zwarte Cross", level-1);
                case "NR:YW3J38":return abstraheren("Zwarte Cross", level-1);
                case "NR:HU8202":return abstraheren("Stadjershal", level-1);
                case "NR:33N101":return abstraheren("Style Coiffures", level-1);
                case "NR:K9Z6T5":return abstraheren("Subway Brugstraat", level-1);
                case "NR:6LCL2C":return abstraheren("Subway Zuiderdiep", level-1);
                case "NR:13ZGB5":return abstraheren("Supermarkt", level-1);
                case "NR:SC3702":return abstraheren("Supermarkt", level-1);
                case "NR:229H42":return abstraheren("Tamoil", level-1);
                case "NR:18744611":return abstraheren("Tankstation Peizerwold", level-1);
                case "NR:QDM2FH":return abstraheren("Taxi", level-1);
                case "NR:10031511":return abstraheren("Texaco", level-1);
                case "NR:21138752":return abstraheren("Tinq", level-1);
                case "NR:21055951":return abstraheren("Tinq", level-1);
                case "NR:21055952":return abstraheren("Tinq", level-1);
                case "NR:9R286V":return abstraheren("Weekendje Van Eekhout", level-1);
                case "NR:QHK7FZ":return abstraheren("Total Dorenbos", level-1);
                case "NR:74038394":return abstraheren("Total", level-1);
                case "NR:22201206":return abstraheren("AC/DC Hamburg", level-1);
                case "NR:94M9XY":return abstraheren("Tuinland", level-1);
                case "NR:9L20P0":return abstraheren("Twin Seasons", level-1);
                case "NR:YTS7Q5":return abstraheren("Apenheul", level-1);
                case "NR:00001011":return abstraheren("Paasweekend Keulen", level-1);
                case "NR:P8J157":return abstraheren("Krukken", level-1);
                case "NR:59P456":return abstraheren("Vis", level-1);
                case "NR:S1A492":return abstraheren("Pinnen", level-1);
                case "NR:S1Q220":return abstraheren("Pinnen", level-1);
                case "NR:S1Q221":return abstraheren("Pinnen", level-1);
                case "NR:Q4M839":return abstraheren("Vis", level-1);
                case "NR:3HD801":return abstraheren("Marktslager", level-1);
                case "NR:1XH901":return abstraheren("Sigarenmagazijn Heemstra", level-1);
                case "NR:3SGK6V":return abstraheren("Vrijbuiter", level-1);
                case "NR:0P098G":return abstraheren("W.C.G. Ordelman", level-1);
                case "NR:G30R21":return abstraheren("WC Paddepoel Groningen", level-1);
                case "NR:VP3901":return abstraheren("Hubo", level-1);
                case "NR:S1N259":return abstraheren("Pinnen", level-1);
                case "NR:00001908":return abstraheren("Zeeman", level-1);
                case "NR:HH7501":return abstraheren("Ziengs", level-1);
                case "NR:3V58Z3":return abstraheren("Albert Heijn", level-1);
                case "NR:W4B2L0":return abstraheren("Albert Heijn", level-1);
                case "NR:W4WYV5":return abstraheren("Albert Heijn", level-1);
                case "NR:W50HT1":return abstraheren("Albert Heijn", level-1);
                case "NR:W99GZD":return abstraheren("Albert Heijn", level-1);
                case "NR:WB65LX":return abstraheren("Albert Heijn", level-1);
                case "NR:574C42":return abstraheren("Albert Heijn", level-1);
                case "NR:547K3N":return abstraheren("Albert Heijn", level-1);
                case "NR:534ZQ7":return abstraheren("Albert Heijn", level-1);
                case "NR:57WSH2":return abstraheren("Albert Heijn", level-1);
                case "NR:960YN0":return abstraheren("Albert Heijn", level-1);
                case "NR:C897HK":return abstraheren("Albert Heijn", level-1);
                case "NR:H8YW15":return abstraheren("Albert Heijn", level-1);
                case "NR:NRN381":return abstraheren("Albert Heijn", level-1);
                case "NR:DFR405":return abstraheren("Albert Heijn", level-1);
                case "NR:7SKH5V":return abstraheren("Albert Heijn", level-1);
                case "NR:P9PBZ6":return abstraheren("Albert Heijn", level-1);
                case "NR:Y6B5BJ":return abstraheren("Albert Heijn", level-1);
                case "NR:3ZWG01":return abstraheren("Blokker", level-1);
                case "NR:CT436503":return abstraheren("De Pintelier", level-1);
                case "NR:CT601336":return abstraheren("Drie gezusters", level-1);
                case "NR:CT602448":return abstraheren("Het Pakhuis", level-1);
                case "NR:CT451819":return abstraheren("Noorderzon", level-1);
                case "NR:CT600208":return abstraheren("Subway", level-1);
                case "NR:CT447906":return abstraheren("Vof De Marktslager", level-1);
                case "NR:98PK8Y":return abstraheren("Coop", level-1);
                case "NR:5CN3XM":return abstraheren("Coop Lubbers", level-1);
                case "NR:5BSD2L":return abstraheren("Coop Lubbers", level-1);
                case "NR:5B6LL8":return abstraheren("Coop Lubbers", level-1);
                case "NR:71060606":return abstraheren("Tankstation De Panjerd", level-1);
                case "NR:S1M239":return abstraheren("Pinnen", level-1);
                case "NR:KC3D59":return abstraheren("Noorderzon", level-1);
                case "NR:ZH0LS5":return abstraheren("Noorderzon", level-1);
                case "NR:FY6501":return abstraheren("Gamma", level-1);
                case "NR:21010912":return abstraheren("Gulf", level-1);
                case "NR:M5L43N":return abstraheren("Hockeybal", level-1);
                case "NR:BQS2M9":return abstraheren("Kantine De Fruithof", level-1);
                case "NR:M9HG5W":return abstraheren("Kardinge", level-1);
                case "NR:9W4MWB":return abstraheren("Knol's Koek", level-1);
                case "NR:24KX03":return abstraheren("Kruidvat", level-1);
                case "NR:3DBZ02":return abstraheren("Leen Bakker", level-1);
                case "NR:4L1302":return abstraheren("Lidl", level-1);
                case "NR:NR55B7":return abstraheren("McDonald's", level-1);
                case "NR:HV8S39":return abstraheren("McDonald's", level-1);
                case "NR:NW694Y":return abstraheren("McDonald's", level-1);
                case "NR:126N91":return abstraheren("Papiermolen", level-1);
                case "NR:0TB860":return abstraheren("Parking Boterdiep", level-1);
                case "NR:67P09D":return abstraheren("Parking Centrum", level-1);
                case "NR:4WZZ02":return abstraheren("Sodexo", level-1);
                case "NR:09GX01":return abstraheren("Kardinge", level-1);
                case "NR:0P797Q":return abstraheren("Subway", level-1);
                case "NR:650S2Z":return abstraheren("Tango", level-1);
                case "NR:XPJ7FT":return abstraheren("Weerterbergen", level-1);
                case "NR:VS8101":return abstraheren("Toko Melati", level-1);
                case "NR:D596P7":return abstraheren("Vof Dorland", level-1);
                case "NR:AQ5907":return abstraheren("Weerterbergen", level-1);
                case "NR:544N6P":return abstraheren("Weerterbergen", level-1);
                case "NR:6L0CQR":return abstraheren("Weerterbergen", level-1);
                case "NR:AQ5913":return abstraheren("Weerterbergen", level-1);
                case "NR:30D32V":return abstraheren("Weerterbergen", level-1);
                case "NR:0MZF56":return abstraheren("Weerterbergen", level-1);
                case "NR:0JCK02":return abstraheren("Wibra", level-1);
                case "NR:72DS02":return abstraheren("Xenos", level-1);
                case "NR:00002021":return abstraheren("Zeeman", level-1);
//
                case "NL98ZZZ271112510000": return abstraheren("Aegon Hypotheek", level-1);
                case "NL89RABO0341090417": return abstraheren("RY Jansma", level-1);
                case "NL13ZZZ332005960000": return abstraheren("Credit Card", level-1);
                case "NL81ABNA0540200735": return abstraheren("LJ van Eekhout Spaarrekening", level-1);
                case "NL73INGB0004799527": return abstraheren("CC van Eekhout", level-1);
                case "NL10ZZZ302086370000": return abstraheren("Zilveren Kruis", level-1);
                case "NL60RABO0312205503": return abstraheren("Weerterbergen", level-1);
                case "NL45RABO0306545241": return abstraheren("Lening auto", level-1);
                case "NL90223130416110000": return abstraheren("Essent Retail Energy", level-1);
                case "NL87ZZZ011718240000": return abstraheren("Gemeente Groningen", level-1);
                case "NL60ZZZ321410680000": return abstraheren("Inshared", level-1);
                case "NL26RABO0140251111": return abstraheren("Inshared", level-1);
                case "NL13ABNA0506417344": return abstraheren("ABN AMRO Tikkie", level-1);
                case "NL30ZZZ333034790000": return abstraheren("Ziggo", level-1);
                case "NL29ZZZ011574870000": return abstraheren("Renshu", level-1);
                case "NL98ZZZ020086210000": return abstraheren("Waterbedrijf Groningen", level-1);
                case "NL85ZZZ140522640000": return abstraheren("Vodafone", level-1);
                case "NL05ZZZ412014630000": return abstraheren("Save the Children", level-1);
                case "NL02ZZZ271084360000": return abstraheren("Oxfam Novib", level-1);
                case "GB96NFXSDDCHAS00000041302392": return abstraheren("Netflix", level-1);
                case "NL32ABNA0242244777": return abstraheren("Essent Retail Energy", level-1);
                case "NL09INGB0000435000": return abstraheren("Aegon Salaris", level-1);
                case "NL27RABO0317087428": return abstraheren("Marcel Moorman", level-1);
                case "NL08RABO0320257924": return abstraheren("RY Jansma", level-1);
                case "NL36INGB0003445588": return abstraheren("Belastingdienst Teruggaaf", level-1);
                case "NL74INGB0004349817": return abstraheren("Matthijs de Vries", level-1);

// LEVEL2
                case "Aldi": return abstraheren("Boodschappen", level-1);
                case "Albert Heijn": return abstraheren("Boodschappen", level-1);
                case "Blokker": return abstraheren("Boodschappen", level-1);
                case "Brasserie vd Berg": return abstraheren("Vakantie", level-1);
                case "Coop": return abstraheren("Boodschappen", level-1);
                case "Coop Lubbers": return abstraheren("Boodschappen", level-1);
                case "Cafe de Bres": return abstraheren("Zuipen", level-1);
                case "Cafe De Keyzer": return abstraheren("Zuipen", level-1);
                case "Cafe de Koffer": return abstraheren("Zuipen", level-1);
                case "Cafe de Minnaar": return abstraheren("Zuipen", level-1);
                case "Cafe de Pintelier": return abstraheren("Zuipen", level-1);
                case "Cafe Mulder": return abstraheren("Zuipen", level-1);
                case "Cafe Ome Ko": return abstraheren("Zuipen", level-1);
                case "Cafe Tante Truus": return abstraheren("Zuipen", level-1);
                case "Cafetaria Friet van Piet": return abstraheren("Zuipen", level-1);
                case "De Pintelier": return abstraheren("Zuipen", level-1);
                case "Drie gezusters": return abstraheren("Zuipen", level-1);
                case "Gamma": return abstraheren("klussen", level-1);
                case "Gulf": return abstraheren("Tanken", level-1);
                case "Het Pakhuis": return abstraheren("Zuipen", level-1);
                case "Hockeybal": return abstraheren("Sport", level-1);
                case "Jumbo": return abstraheren("Boodschappen", level-1);
                case "Kantine De Fruithof": return abstraheren("Sport", level-1);
                case "Kardinge": return abstraheren("Sport", level-1);
                case "Knol's Koek": return abstraheren("Boodschappen", level-1);
                case "Kruidvat": return abstraheren("Boodschappen", level-1);
                case "Le Souk": return abstraheren("Boodschappen", level-1);
                case "Leen Bakker": return abstraheren("klussen", level-1);
                case "Lidl": return abstraheren("Boodschappen", level-1);
                case "McDonald's": return abstraheren("Uiteten", level-1);
                case "Noorderzon": return abstraheren("Vakantie", level-1);
                case "Papiermolen": return abstraheren("Sport", level-1);
                case "Parking Boterdiep": return abstraheren("Parkeren", level-1);
                case "Parking Centrum": return abstraheren("Parkeren", level-1);
                case "Philips Museum": return abstraheren("Vakantie", level-1);
                case "Poiesz": return abstraheren("Boodschappen", level-1);
                case "Smedema's Poeliersbedrijf": return abstraheren("Boodschappen", level-1);
                case "Sodexo": return abstraheren("Uiteten", level-1);
                case "Subway": return abstraheren("Uiteten", level-1);
                case "Tamoil": return abstraheren("Tanken", level-1);
                case "Tango": return abstraheren("Tanken", level-1);
                case "Tankstation De Panjerd": return abstraheren("Tanken", level-1);
                case "Toko Melati": return abstraheren("Boodschappen", level-1);
                case "Visspecialist Paddepoel": return abstraheren("Boodschappen", level-1);
                case "Vof De Marktslager": return abstraheren("Boodschappen", level-1);
                case "Vof Dorland": return abstraheren("Boodschappen", level-1);
                case "Weerterbergen": return abstraheren("Vakantie", level-1);
                case "Wibra": return abstraheren("Boodschappen", level-1);
                case "Xenos": return abstraheren("Boodschappen", level-1);
                case "Zeeman": return abstraheren("Boodschappen", level-1);
                case "Save the Children": return abstraheren("Goede doel", level-1);
                case "Oxfam Novib": return abstraheren("Goede doel", level-1);

                default: return key;
            }
        }
    }
}
